//! The tray icon set. Embedded in the binary and written out at startup as a
//! small icon theme, so the panel can load the icons by name and recolour them.
//! The SVGs are generated by assets/brand/tray-icons.py (state icons) and
//! assets/brand/bus-icons.py (the dashboard's bus tiles).

use crate::status::TrayState;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub(crate) const ICONS: [(&str, &str); 14] = [
    (
        "plugkill-armed-symbolic",
        include_str!("../icons/plugkill-armed-symbolic.svg"),
    ),
    (
        "plugkill-learning-symbolic",
        include_str!("../icons/plugkill-learning-symbolic.svg"),
    ),
    (
        "plugkill-disarmed-symbolic",
        include_str!("../icons/plugkill-disarmed-symbolic.svg"),
    ),
    (
        "plugkill-pending-symbolic",
        include_str!("../icons/plugkill-pending-symbolic.svg"),
    ),
    (
        "plugkill-pending-blink-symbolic",
        include_str!("../icons/plugkill-pending-blink-symbolic.svg"),
    ),
    (
        "plugkill-down-symbolic",
        include_str!("../icons/plugkill-down-symbolic.svg"),
    ),
    (
        "plugkill-bus-usb-symbolic",
        include_str!("../icons/plugkill-bus-usb-symbolic.svg"),
    ),
    (
        "plugkill-bus-thunderbolt-symbolic",
        include_str!("../icons/plugkill-bus-thunderbolt-symbolic.svg"),
    ),
    (
        "plugkill-bus-sdcard-symbolic",
        include_str!("../icons/plugkill-bus-sdcard-symbolic.svg"),
    ),
    (
        "plugkill-bus-power-symbolic",
        include_str!("../icons/plugkill-bus-power-symbolic.svg"),
    ),
    (
        "plugkill-bus-network-symbolic",
        include_str!("../icons/plugkill-bus-network-symbolic.svg"),
    ),
    (
        "plugkill-bus-lid-symbolic",
        include_str!("../icons/plugkill-bus-lid-symbolic.svg"),
    ),
    (
        "plugkill-bus-pci-symbolic",
        include_str!("../icons/plugkill-bus-pci-symbolic.svg"),
    ),
    (
        "plugkill-bus-display-symbolic",
        include_str!("../icons/plugkill-bus-display-symbolic.svg"),
    ),
];

const INDEX_THEME: &str = "[Icon Theme]
Name=plugkill
Comment=plugkill tray icons
Directories=scalable/status

[scalable/status]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=Status
";

/// The icon for `state`. A pending kill alternates between two icons; every
/// other state ignores `blink_on`. A dry run shares the learning icon because
/// both mean the same thing for the machine: watched, never killed.
pub fn icon_name(state: &TrayState, blink_on: bool) -> &'static str {
    match state {
        TrayState::Armed => "plugkill-armed-symbolic",
        TrayState::Learning | TrayState::DryRun => "plugkill-learning-symbolic",
        TrayState::Disarmed { .. } => "plugkill-disarmed-symbolic",
        TrayState::KillPending { .. } if blink_on => "plugkill-pending-blink-symbolic",
        TrayState::KillPending { .. } => "plugkill-pending-symbolic",
        TrayState::Down { .. } => "plugkill-down-symbolic",
    }
}

/// Write the icons under `root` as a hicolor theme, plus an unthemed copy of
/// each at the top level for hosts that only look there.
pub fn install(root: &Path) -> io::Result<()> {
    let theme = root.join("hicolor");
    let status_dir = theme.join("scalable").join("status");
    fs::create_dir_all(&status_dir)?;
    fs::write(theme.join("index.theme"), INDEX_THEME)?;
    for (name, svg) in ICONS {
        fs::write(status_dir.join(format!("{name}.svg")), svg)?;
        fs::write(root.join(format!("{name}.svg")), svg)?;
    }
    Ok(())
}

/// `$XDG_RUNTIME_DIR/plugkill-gui/icons`. None when the variable is unset:
/// the runtime dir is private to the user, and a shared temp dir is not a
/// safe substitute.
pub fn default_root() -> Option<PathBuf> {
    std::env::var_os("XDG_RUNTIME_DIR")
        .map(|dir| PathBuf::from(dir).join("plugkill-gui").join("icons"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn every_state() -> Vec<TrayState> {
        vec![
            TrayState::Down { stalled: false },
            TrayState::Down { stalled: true },
            TrayState::Disarmed { secs_left: 10 },
            TrayState::KillPending {
                bus: "power".into(),
                reason: "AC power removed".into(),
                secs_left: 5,
            },
            TrayState::DryRun,
            TrayState::Learning,
            TrayState::Armed,
        ]
    }

    fn svg_of(name: &str) -> &'static str {
        ICONS
            .iter()
            .find(|(n, _)| *n == name)
            .expect("icon exists")
            .1
    }

    #[test]
    fn test_every_state_maps_to_an_embedded_icon() {
        for state in every_state() {
            for blink in [false, true] {
                let name = icon_name(&state, blink);
                assert!(
                    ICONS.iter().any(|(n, _)| *n == name),
                    "{state:?} maps to {name}, which is not embedded"
                );
            }
        }
    }

    #[test]
    fn test_only_a_pending_kill_blinks() {
        for state in every_state() {
            let blinks = icon_name(&state, false) != icon_name(&state, true);
            assert_eq!(
                blinks,
                matches!(state, TrayState::KillPending { .. }),
                "{state:?}"
            );
        }
    }

    #[test]
    fn test_icons_survive_symbolic_recolouring() {
        let buses = ICONS
            .iter()
            .filter(|(n, _)| n.starts_with("plugkill-bus-"))
            .count();
        assert_eq!(buses, plugkill_core::ipc::BUSES.len());
        for (name, svg) in ICONS {
            assert!(name.ends_with("-symbolic"), "{name}");
            // State icons are tray sized; bus icons sit in 16 px tiles in one colour.
            if name.starts_with("plugkill-bus-") {
                assert!(svg.contains(r#"viewBox="0 0 16 16""#), "{name}");
                let fg = r#"<path class="ColorScheme-Text" fill="currentColor""#;
                assert_eq!(
                    svg.matches("<path").count(),
                    svg.matches(fg).count(),
                    "{name}"
                );
                assert!(svg.contains(fg), "{name} draws nothing");
            } else {
                assert!(svg.contains(r#"viewBox="0 0 22 22""#), "{name}");
            }
            assert!(!svg.contains("stroke"), "{name} draws with stroke");
            assert!(
                !svg.to_lowercase().contains("#fff"),
                "{name} uses a white fill"
            );
        }
    }

    #[test]
    fn test_colour_classes_follow_the_severity_ladder() {
        for name in ["plugkill-armed-symbolic", "plugkill-down-symbolic"] {
            let svg = svg_of(name);
            assert!(!svg.contains("warning") && !svg.contains("error"), "{name}");
        }
        for name in ["plugkill-learning-symbolic", "plugkill-disarmed-symbolic"] {
            let svg = svg_of(name);
            assert!(
                svg.contains(r#"class="warning"#) && !svg.contains("error"),
                "{name}"
            );
        }
        for name in [
            "plugkill-pending-symbolic",
            "plugkill-pending-blink-symbolic",
        ] {
            assert!(svg_of(name).contains(r#"class="error"#), "{name}");
        }
    }

    #[test]
    fn test_install_writes_a_hicolor_theme_and_flat_copies() {
        let dir = tempfile::tempdir().unwrap();
        install(dir.path()).unwrap();
        assert!(dir.path().join("hicolor/index.theme").is_file());
        for (name, svg) in ICONS {
            let themed = dir
                .path()
                .join(format!("hicolor/scalable/status/{name}.svg"));
            assert_eq!(fs::read_to_string(themed).unwrap(), svg);
            assert!(dir.path().join(format!("{name}.svg")).is_file());
        }
    }
}
