//! The compact right-click menu as plain data. `tray.rs` turns it into ksni
//! items; keeping ksni out of the model keeps its wording and order testable.

use crate::commands::{Command, DISARM_PRESETS, MAX_DISARM_SECS};
use crate::dashboard::model::tile_value;
use crate::status::format_uptime;
use crate::status::{Status, TrayState};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MenuAction {
    OpenDashboard,
    OpenSettings,
    Command(Command),
    Quit,
}

/// Every `icon` below names a PNG that `tray.rs` embeds, generated by
/// assets/brand/menu-icons.py.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Entry {
    /// The first line: state and detail. Not clickable.
    Header {
        text: String,
        icon: &'static str,
    },
    /// A secondary line. Not clickable, and never carries an icon.
    Info(String),
    Separator,
    Action {
        label: String,
        action: MenuAction,
        icon: &'static str,
    },
    Submenu {
        label: String,
        children: Vec<Entry>,
        icon: &'static str,
    },
    /// Mutually exclusive options; `selected` indexes `options`. Every option
    /// wears the same icon.
    Radio {
        options: Vec<(String, MenuAction)>,
        selected: usize,
        icon: &'static str,
    },
    /// A read-only checkmark row.
    Check {
        label: String,
        checked: bool,
        icon: &'static str,
    },
}

/// The watched and unwatched icon of each bus, in `ipc::BUSES` order. Same
/// glyph in the same grey either way; the watched one wears a green dot, so
/// the submenu can be read without counting checkmarks. A test keeps the list
/// in step with `ipc::BUSES`.
const BUS_ICONS: [(&str, &str); 8] = [
    ("usb-on", "usb-off"),
    ("thunderbolt-on", "thunderbolt-off"),
    ("sdcard-on", "sdcard-off"),
    ("power-on", "power-off"),
    ("network-on", "network-off"),
    ("lid-on", "lid-off"),
    ("pci-on", "pci-off"),
    ("display-on", "display-off"),
];

/// `notice` is the last command's refusal, shown under the header until a
/// command works. It never changes the state above it: a refused disarm leaves
/// the menu saying armed, because the daemon still is.
pub fn build(state: &TrayState, status: Option<&Status>, notice: Option<&str>) -> Vec<Entry> {
    let (title, detail) = state.title_and_detail(status);
    let header_icon = state_icon(state);
    let notice = notice.map(|n| Entry::Info(n.to_string()));
    let status = match (state, status) {
        (TrayState::Down { .. }, _) | (_, None) => {
            let mut entries = vec![
                Entry::Header {
                    text: title,
                    icon: header_icon,
                },
                Entry::Info(detail),
            ];
            entries.extend(notice);
            // Quit gets its own block here too, so it is never the row right
            // under the one everybody clicks.
            entries.extend([
                Entry::Separator,
                action("Open dashboard", MenuAction::OpenDashboard, "dashboard"),
                // Settings is offered with the daemon down as well: its
                // diagnostics panel is for exactly that.
                action("Settings", MenuAction::OpenSettings, "maintenance"),
                Entry::Separator,
                action("Quit tray", MenuAction::Quit, "quit"),
            ]);
            return entries;
        }
        (_, Some(s)) => s,
    };

    let mut info = format!("Up {}", format_uptime(status.uptime_secs));
    if let Some(ms) = status.last_poll_ms_ago {
        info.push_str(&format!(", polled {ms} ms ago"));
    }

    let mut entries = vec![
        Entry::Header {
            text: format!("{title}, {detail}"),
            icon: header_icon,
        },
        Entry::Info(info),
    ];
    entries.extend(notice);
    entries.extend([
        Entry::Separator,
        action("Open dashboard", MenuAction::OpenDashboard, "dashboard"),
        action("Settings", MenuAction::OpenSettings, "maintenance"),
        Entry::Separator,
    ]);

    // While disarmed, the two items that undo it wear the disarmed orange.
    if matches!(state, TrayState::Disarmed { .. }) {
        entries.push(action(
            "Arm now",
            MenuAction::Command(Command::Arm),
            "shield-disarmed",
        ));
        // The daemon replaces the disarm deadline rather than adding to it, so
        // "extend" has to send what is left plus the preset. Without that, a
        // preset shorter than the remaining time would re-arm the machine early.
        entries.push(disarm_presets(
            "Extend disarm",
            status.disarm_remaining_secs.unwrap_or(0),
            "clock-disarmed",
        ));
    } else {
        entries.push(action(
            "Disarm for 5 minutes",
            MenuAction::Command(Command::Disarm(300)),
            "clock",
        ));
        entries.push(disarm_presets("Disarm for", 0, "clock"));
    }
    entries.push(Entry::Separator);

    let learning = status.mode == "learn";
    entries.push(Entry::Submenu {
        label: "Mode".into(),
        // A state colour only appears when the state is what it names: a
        // disarmed or pending daemon in enforce mode kills nothing, so the row
        // stays neutral rather than wearing the armed green.
        icon: match state {
            TrayState::Learning | TrayState::DryRun => "shield-learn",
            TrayState::Armed => "shield-enforce",
            _ => "shield",
        },
        children: vec![Entry::Radio {
            options: vec![
                ("Enforce".into(), MenuAction::Command(Command::Enforce)),
                ("Learn".into(), MenuAction::Command(Command::Learn)),
            ],
            selected: usize::from(learning),
            icon: "shield",
        }],
    });

    let buses = status.buses();
    let watched = buses.iter().filter(|b| b.2).count();
    entries.push(Entry::Submenu {
        label: format!("Watching {watched} of {}", buses.len()),
        icon: "eye",
        children: buses
            .iter()
            .zip(BUS_ICONS)
            .map(|(&(key, name, on), (yes, no))| Entry::Check {
                label: format!("{name}: {}", tile_value(status, key, on)),
                // The dot is for scanning, the checkmark is what a screen
                // reader reads. Both say the same thing.
                checked: on,
                icon: if on { yes } else { no },
            })
            .collect(),
    });

    match status.violations_logged {
        0 => {}
        1 => entries.push(Entry::Info("1 violation logged".into())),
        n => entries.push(Entry::Info(format!("{n} violations logged"))),
    }

    // Quit sat one row under the everyday items and was hit by accident. Both
    // maintenance items now cost a second, deliberate click.
    entries.extend([
        Entry::Separator,
        Entry::Submenu {
            label: "Maintenance".into(),
            icon: "maintenance",
            children: vec![
                action(
                    "Reload config",
                    MenuAction::Command(Command::Reload),
                    "refresh",
                ),
                action("Quit tray", MenuAction::Quit, "quit"),
            ],
        },
    ]);
    entries
}

fn action(label: &str, action: MenuAction, icon: &'static str) -> Entry {
    Entry::Action {
        label: label.to_string(),
        action,
        icon,
    }
}

/// The preset submenu. `add` is what a preset is added to, the seconds left on
/// a running disarm; the daemon caps a request at `MAX_DISARM_SECS`. `icon` is
/// the row's own, the presets inside stay neutral.
fn disarm_presets(label: &str, add: u64, icon: &'static str) -> Entry {
    Entry::Submenu {
        label: label.to_string(),
        icon,
        children: DISARM_PRESETS
            .iter()
            .map(|&(secs, long, _)| {
                let secs = secs.saturating_add(add).min(MAX_DISARM_SECS);
                action(long, MenuAction::Command(Command::Disarm(secs)), "clock")
            })
            .collect(),
    }
}

/// The header wears the state the tray icon shows.
fn state_icon(state: &TrayState) -> &'static str {
    match state {
        TrayState::Armed => "armed",
        TrayState::Learning | TrayState::DryRun => "learning",
        TrayState::Disarmed { .. } => "disarmed",
        TrayState::KillPending { .. } => "pending",
        TrayState::Down { .. } => "down",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn status(extra: serde_json::Value) -> Status {
        let mut data = serde_json::json!({"armed": true, "mode": "enforce", "uptime_secs": 65});
        data.as_object_mut()
            .unwrap()
            .extend(extra.as_object().unwrap().clone());
        serde_json::from_value(data).unwrap()
    }

    fn labels(entries: &[Entry]) -> Vec<String> {
        entries
            .iter()
            .filter_map(|e| match e {
                Entry::Header { text, .. } | Entry::Info(text) => Some(text.clone()),
                Entry::Action { label, .. } | Entry::Submenu { label, .. } => Some(label.clone()),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn test_down_menu_offers_only_the_windows_and_quit() {
        let entries = build(&TrayState::Down { stalled: false }, None, None);
        assert_eq!(
            entries,
            vec![
                Entry::Header {
                    text: "Daemon not running".into(),
                    icon: "down"
                },
                Entry::Info("no answer on the control socket".into()),
                Entry::Separator,
                action("Open dashboard", MenuAction::OpenDashboard, "dashboard"),
                action("Settings", MenuAction::OpenSettings, "maintenance"),
                Entry::Separator,
                action("Quit tray", MenuAction::Quit, "quit"),
            ]
        );
    }

    #[test]
    fn test_settings_is_one_click_away_whatever_the_daemon_says() {
        let up = build(
            &TrayState::Armed,
            Some(&status(serde_json::json!({}))),
            None,
        );
        for entries in [&up, &build(&TrayState::Down { stalled: false }, None, None)] {
            assert!(
                entries.contains(&action("Settings", MenuAction::OpenSettings, "maintenance")),
                "no Settings row: {entries:?}"
            );
        }
    }

    #[test]
    fn test_armed_menu_leads_with_state_then_disarm() {
        let s = status(serde_json::json!({"last_poll_ms_ago": 180}));
        let entries = build(&TrayState::Armed, Some(&s), None);
        assert_eq!(
            labels(&entries)[..6],
            [
                "Armed, enforce mode",
                "Up 1m, polled 180 ms ago",
                "Open dashboard",
                "Settings",
                "Disarm for 5 minutes",
                "Disarm for",
            ]
        );
        assert!(entries.contains(&action(
            "Disarm for 5 minutes",
            MenuAction::Command(Command::Disarm(300)),
            "clock"
        )));
        assert!(!labels(&entries).contains(&"Arm now".to_string()));
    }

    #[test]
    fn test_a_refused_disarm_is_said_out_loud_and_the_state_stays_armed() {
        let s = status(serde_json::json!({"last_poll_ms_ago": 180}));
        let notice = "Disarm refused: authentication required";
        let entries = build(&TrayState::Armed, Some(&s), Some(notice));

        assert_eq!(
            labels(&entries)[..3],
            ["Armed, enforce mode", "Up 1m, polled 180 ms ago", notice,]
        );
        // The refusal reads, it does not act: still armed, still offering disarm.
        assert!(matches!(entries[0], Entry::Header { icon: "armed", .. }));
        assert!(labels(&entries).contains(&"Disarm for 5 minutes".to_string()));
    }

    #[test]
    fn test_a_refusal_with_no_daemon_answer_still_shows() {
        let entries = build(
            &TrayState::Down { stalled: false },
            None,
            Some("Reload failed: x"),
        );
        assert_eq!(labels(&entries)[2], "Reload failed: x");
    }

    #[test]
    fn test_disarmed_menu_offers_arm_now_and_extend() {
        let s = status(serde_json::json!({"armed": false, "disarm_remaining_secs": 252}));
        let entries = build(&TrayState::Disarmed { secs_left: 252 }, Some(&s), None);
        assert!(entries.contains(&action(
            "Arm now",
            MenuAction::Command(Command::Arm),
            "shield-disarmed"
        )));
        let extend = entries
            .iter()
            .find_map(|e| match e {
                Entry::Submenu {
                    label, children, ..
                } if label == "Extend disarm" => Some(children),
                _ => None,
            })
            .expect("extend submenu");
        assert_eq!(extend.len(), DISARM_PRESETS.len());
        // Extending must never shorten a running disarm: every preset asks for
        // at least what is left, capped at what the daemon accepts.
        for entry in extend {
            let Entry::Action {
                action: MenuAction::Command(Command::Disarm(secs)),
                ..
            } = entry
            else {
                panic!("a preset must send a disarm: {entry:?}");
            };
            assert!(*secs >= 252.min(MAX_DISARM_SECS), "{entry:?}");
            assert!(*secs <= MAX_DISARM_SECS, "{entry:?}");
        }
        assert!(extend.contains(&action(
            "1 minute",
            MenuAction::Command(Command::Disarm(312)),
            "clock"
        )));
    }

    #[test]
    fn test_mode_radio_reflects_learn_and_violations_are_listed() {
        let s = status(serde_json::json!({"mode": "learn", "violations_logged": 3}));
        let entries = build(&TrayState::Learning, Some(&s), None);
        let radio = entries
            .iter()
            .find_map(|e| match e {
                Entry::Submenu {
                    label, children, ..
                } if label == "Mode" => children.first(),
                _ => None,
            })
            .expect("mode submenu");
        assert!(matches!(radio, Entry::Radio { selected: 1, .. }));
        assert!(entries.contains(&Entry::Info("3 violations logged".into())));
    }

    #[test]
    fn test_watching_submenu_counts_and_reads_buses() {
        let s = status(serde_json::json!({
            "usb_watching": true, "usb_devices": 4,
            "power_watching": true, "power_state": "ac",
            "lid_watching": true, "lid_state": "open",
            "network_watching": true, "network_links_down": 2,
            "pci_devices": 23
        }));
        let entries = build(&TrayState::Armed, Some(&s), None);
        let (label, children) = entries
            .iter()
            .find_map(|e| match e {
                Entry::Submenu {
                    label, children, ..
                } if label.starts_with("Watching") => Some((label, children)),
                _ => None,
            })
            .expect("watching submenu");
        assert_eq!(label, "Watching 4 of 8");
        assert_eq!(
            children[0],
            Entry::Check {
                label: "USB: 4".into(),
                checked: true,
                icon: "usb-on"
            }
        );
        // The dot on the icon and the checkmark must never disagree.
        for child in children {
            let Entry::Check { checked, icon, .. } = child else {
                panic!("a bus row must be a checkmark: {child:?}");
            };
            assert_eq!(*checked, icon.ends_with("-on"), "{child:?}");
        }
        assert!(children.contains(&Entry::Check {
            label: "Thunderbolt: off".into(),
            checked: false,
            icon: "thunderbolt-off"
        }));
        let readings: Vec<&str> = children
            .iter()
            .filter_map(|e| match e {
                Entry::Check { label, .. } => Some(label.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(
            readings,
            [
                "USB: 4",
                "Thunderbolt: off",
                "SD card: off",
                "Power supply: on AC",
                "Network: 2 down",
                "Lid: open",
                "PCI: off",
                "Display: off",
            ]
        );
    }

    #[test]
    fn test_a_watched_network_with_every_link_up_reads_link_up() {
        let s = status(serde_json::json!({
            "network_watching": true, "network_links_down": 0, "display_watching": true
        }));
        let entries = build(&TrayState::Armed, Some(&s), None);
        let children = entries
            .iter()
            .find_map(|e| match e {
                Entry::Submenu {
                    label, children, ..
                } if label.starts_with("Watching") => Some(children),
                _ => None,
            })
            .expect("watching submenu");
        assert!(children.contains(&Entry::Check {
            label: "Network: link up".into(),
            checked: true,
            icon: "network-on"
        }));
        // A watched bus the daemon reports nothing about reads the tile fallback.
        assert!(children.contains(&Entry::Check {
            label: "Display: watching".into(),
            checked: true,
            icon: "display-on"
        }));
    }

    #[test]
    fn test_bus_icons_follow_the_bus_list() {
        assert_eq!(BUS_ICONS.len(), plugkill_core::ipc::BUSES.len());
        for (&(key, _), (yes, no)) in plugkill_core::ipc::BUSES.iter().zip(BUS_ICONS) {
            let bus = key.strip_suffix("_watching").unwrap();
            assert_eq!(yes, format!("{bus}-on"));
            assert_eq!(no, format!("{bus}-off"));
        }
    }

    fn icon_of(entries: &[Entry], wanted: &str) -> &'static str {
        entries
            .iter()
            .find_map(|e| match e {
                Entry::Action { label, icon, .. } | Entry::Submenu { label, icon, .. }
                    if label == wanted =>
                {
                    Some(*icon)
                }
                _ => None,
            })
            .unwrap_or_else(|| panic!("no {wanted} row"))
    }

    #[test]
    fn test_the_mode_row_is_tinted_with_the_live_mode() {
        let enforce = status(serde_json::json!({}));
        assert_eq!(
            icon_of(&build(&TrayState::Armed, Some(&enforce), None), "Mode"),
            "shield-enforce"
        );
        let learn = status(serde_json::json!({"mode": "learn"}));
        assert_eq!(
            icon_of(&build(&TrayState::Learning, Some(&learn), None), "Mode"),
            "shield-learn"
        );
        // Dry run enforces nothing, so it reads as learn, not as armed.
        let dry = status(serde_json::json!({"dry_run": true}));
        assert_eq!(
            icon_of(&build(&TrayState::DryRun, Some(&dry), None), "Mode"),
            "shield-learn"
        );
        // Disarmed in enforce mode: no colour, the state is not what it names.
        let off = status(serde_json::json!({"armed": false, "disarm_remaining_secs": 60}));
        assert_eq!(
            icon_of(
                &build(&TrayState::Disarmed { secs_left: 60 }, Some(&off), None),
                "Mode"
            ),
            "shield"
        );
    }

    #[test]
    fn test_only_a_disarmed_daemon_tints_the_arm_and_extend_rows() {
        let armed = build(
            &TrayState::Armed,
            Some(&status(serde_json::json!({}))),
            None,
        );
        assert_eq!(icon_of(&armed, "Disarm for 5 minutes"), "clock");
        assert_eq!(icon_of(&armed, "Disarm for"), "clock");

        let s = status(serde_json::json!({"armed": false, "disarm_remaining_secs": 60}));
        let disarmed = build(&TrayState::Disarmed { secs_left: 60 }, Some(&s), None);
        assert_eq!(icon_of(&disarmed, "Arm now"), "shield-disarmed");
        assert_eq!(icon_of(&disarmed, "Extend disarm"), "clock-disarmed");
    }

    #[test]
    fn test_quitting_takes_a_detour_through_maintenance() {
        let entries = build(
            &TrayState::Armed,
            Some(&status(serde_json::json!({}))),
            None,
        );
        // Nothing at the top level quits or reloads: both sit one level down.
        assert!(!entries.iter().any(|e| matches!(
            e,
            Entry::Action {
                action: MenuAction::Quit | MenuAction::Command(Command::Reload),
                ..
            }
        )));
        let Some(Entry::Submenu { children, icon, .. }) = entries.last() else {
            panic!("maintenance must be the last row: {:?}", entries.last());
        };
        assert_eq!(*icon, "maintenance");
        assert_eq!(
            children,
            &vec![
                action(
                    "Reload config",
                    MenuAction::Command(Command::Reload),
                    "refresh"
                ),
                action("Quit tray", MenuAction::Quit, "quit"),
            ]
        );
        // The everyday rows stay one click away.
        for label in ["Open dashboard", "Disarm for 5 minutes", "Mode"] {
            icon_of(&entries, label);
        }
    }
}
