//! The StatusNotifierItem: icon by name, tooltip, and the compact menu.

use crate::commands::Command;
use crate::icons;
use crate::menu::{self, Entry, MenuAction};
use crate::status::format_uptime;
use crate::status::{Status, TrayState};
use ksni::menu::{CheckmarkItem, RadioGroup, RadioItem, StandardItem, SubMenu};
use ksni::{Category, MenuItem, ToolTip};
use log::warn;
use std::time::Instant;

/// What a click in the tray asks the rest of the GUI to do.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayEvent {
    /// Left click. The position is the panel's hint for where to open the dashboard.
    Activate {
        x: i32,
        y: i32,
    },
    OpenDashboard,
    OpenSettings,
    Command(Command),
    Quit,
}

pub struct PlugkillTray {
    pub state: TrayState,
    pub status: Option<Status>,
    pub blink_on: bool,
    /// Why the last command did not run, with the moment it was set: the
    /// poller drops it once it is stale, so a one-off failure does not sit
    /// next to a live state that contradicts it. `state` above is still
    /// whatever the daemon reports, so a refused disarm keeps saying armed.
    pub notice: Option<(String, Instant)>,
    /// Where `icons::install` wrote the icon theme; empty when it could not.
    icon_theme_path: String,
    events: async_channel::Sender<TrayEvent>,
}

impl PlugkillTray {
    pub fn new(icon_theme_path: String, events: async_channel::Sender<TrayEvent>) -> Self {
        Self {
            state: TrayState::Down { stalled: false },
            status: None,
            blink_on: false,
            notice: None,
            icon_theme_path,
            events,
        }
    }

    /// Hand an event to the GUI without blocking the menu.
    fn emit(&self, event: TrayEvent) {
        if self.events.try_send(event).is_err() {
            warn!("tray event dropped, the gui side has stopped");
        }
    }
}

impl ksni::Tray for PlugkillTray {
    // Left click goes to `activate` and opens the dashboard; right click shows the menu.
    const MENU_ON_ACTIVATE: bool = false;

    fn id(&self) -> String {
        "plugkill".into()
    }

    fn category(&self) -> Category {
        Category::SystemServices
    }

    fn title(&self) -> String {
        let (title, _) = self.state.title_and_detail(self.status.as_ref());
        format!("plugkill: {title}")
    }

    fn status(&self) -> ksni::Status {
        if self.state.needs_attention() {
            ksni::Status::NeedsAttention
        } else {
            ksni::Status::Active
        }
    }

    fn icon_theme_path(&self) -> String {
        self.icon_theme_path.clone()
    }

    fn icon_name(&self) -> String {
        icons::icon_name(&self.state, self.blink_on).into()
    }

    fn tool_tip(&self) -> ToolTip {
        let (title, detail) = self.state.title_and_detail(self.status.as_ref());
        let mut lines = vec![detail];
        if let Some(s) = &self.status {
            let buses = s.buses();
            let names: Vec<&str> = buses.iter().filter(|b| b.2).map(|b| b.1).collect();
            lines.push(format!(
                "Watching {} of {}: {}",
                names.len(),
                buses.len(),
                names.join(", ")
            ));
            lines.push(format!("Up {}", format_uptime(s.uptime_secs)));
        }
        ToolTip {
            title: format!("plugkill: {title}"),
            description: lines.join("\n"),
            ..Default::default()
        }
    }

    fn activate(&mut self, x: i32, y: i32) {
        self.emit(TrayEvent::Activate { x, y });
    }

    fn menu(&self) -> Vec<MenuItem<Self>> {
        to_ksni(menu::build(
            &self.state,
            self.status.as_ref(),
            self.notice.as_ref().map(|(text, _)| text.as_str()),
        ))
    }
}

/// The menu icons as 16 by 16 PNGs, keyed by the names `menu.rs` uses. The
/// panel draws the menu and cannot reach our icon theme, so DBusMenu carries
/// the bytes. Generated by assets/brand/menu-icons.py.
/// Each bus comes in two: `-on` carries the armed green dot, `-off` a grey one.
/// The tinted verbs carry the dashboard's state colours.
const MENU_ICONS: [(&str, &[u8]); 32] = [
    ("armed", include_bytes!("../icons/png/armed.png")),
    ("learning", include_bytes!("../icons/png/learning.png")),
    ("disarmed", include_bytes!("../icons/png/disarmed.png")),
    ("pending", include_bytes!("../icons/png/pending.png")),
    ("down", include_bytes!("../icons/png/down.png")),
    ("usb-on", include_bytes!("../icons/png/usb-on.png")),
    ("usb-off", include_bytes!("../icons/png/usb-off.png")),
    (
        "thunderbolt-on",
        include_bytes!("../icons/png/thunderbolt-on.png"),
    ),
    (
        "thunderbolt-off",
        include_bytes!("../icons/png/thunderbolt-off.png"),
    ),
    ("sdcard-on", include_bytes!("../icons/png/sdcard-on.png")),
    ("sdcard-off", include_bytes!("../icons/png/sdcard-off.png")),
    ("power-on", include_bytes!("../icons/png/power-on.png")),
    ("power-off", include_bytes!("../icons/png/power-off.png")),
    ("network-on", include_bytes!("../icons/png/network-on.png")),
    (
        "network-off",
        include_bytes!("../icons/png/network-off.png"),
    ),
    ("lid-on", include_bytes!("../icons/png/lid-on.png")),
    ("lid-off", include_bytes!("../icons/png/lid-off.png")),
    ("pci-on", include_bytes!("../icons/png/pci-on.png")),
    ("pci-off", include_bytes!("../icons/png/pci-off.png")),
    ("display-on", include_bytes!("../icons/png/display-on.png")),
    (
        "display-off",
        include_bytes!("../icons/png/display-off.png"),
    ),
    ("dashboard", include_bytes!("../icons/png/dashboard.png")),
    ("clock", include_bytes!("../icons/png/clock.png")),
    (
        "clock-disarmed",
        include_bytes!("../icons/png/clock-disarmed.png"),
    ),
    ("shield", include_bytes!("../icons/png/shield.png")),
    (
        "shield-enforce",
        include_bytes!("../icons/png/shield-enforce.png"),
    ),
    (
        "shield-learn",
        include_bytes!("../icons/png/shield-learn.png"),
    ),
    (
        "shield-disarmed",
        include_bytes!("../icons/png/shield-disarmed.png"),
    ),
    ("eye", include_bytes!("../icons/png/eye.png")),
    (
        "maintenance",
        include_bytes!("../icons/png/maintenance.png"),
    ),
    ("refresh", include_bytes!("../icons/png/refresh.png")),
    ("quit", include_bytes!("../icons/png/quit.png")),
];

/// An unknown key draws no icon rather than failing the menu; the tests keep
/// the model from producing one.
fn icon_data(key: &str) -> Vec<u8> {
    MENU_ICONS
        .iter()
        .find(|(name, _)| *name == key)
        .map_or_else(Vec::new, |(_, png)| png.to_vec())
}

/// ksni reads a single underscore in a label as an access-key marker.
fn label(text: &str) -> String {
    text.replace('_', "__")
}

fn event_for(action: MenuAction) -> TrayEvent {
    match action {
        MenuAction::OpenDashboard => TrayEvent::OpenDashboard,
        MenuAction::OpenSettings => TrayEvent::OpenSettings,
        MenuAction::Command(command) => TrayEvent::Command(command),
        MenuAction::Quit => TrayEvent::Quit,
    }
}

fn to_ksni(entries: Vec<Entry>) -> Vec<MenuItem<PlugkillTray>> {
    entries
        .into_iter()
        .map(|entry| match entry {
            Entry::Header { text, icon } => StandardItem {
                label: label(&text),
                icon_data: icon_data(icon),
                enabled: false,
                ..Default::default()
            }
            .into(),
            Entry::Info(text) => StandardItem {
                label: label(&text),
                enabled: false,
                ..Default::default()
            }
            .into(),
            Entry::Separator => MenuItem::Separator,
            Entry::Action {
                label: text,
                action,
                icon,
            } => StandardItem {
                label: label(&text),
                icon_data: icon_data(icon),
                activate: Box::new(move |tray: &mut PlugkillTray| tray.emit(event_for(action))),
                ..Default::default()
            }
            .into(),
            Entry::Submenu {
                label: text,
                children,
                icon,
            } => SubMenu {
                label: label(&text),
                icon_data: icon_data(icon),
                submenu: to_ksni(children),
                ..Default::default()
            }
            .into(),
            Entry::Radio {
                options,
                selected,
                icon,
            } => {
                let actions: Vec<MenuAction> = options.iter().map(|(_, a)| *a).collect();
                RadioGroup {
                    selected,
                    select: Box::new(move |tray: &mut PlugkillTray, index| {
                        if let Some(&action) = actions.get(index) {
                            tray.emit(event_for(action));
                        }
                    }),
                    options: options
                        .into_iter()
                        .map(|(text, _)| RadioItem {
                            label: label(&text),
                            icon_data: icon_data(icon),
                            ..Default::default()
                        })
                        .collect(),
                }
                .into()
            }
            Entry::Check {
                label: text,
                checked,
                icon,
            } => CheckmarkItem {
                label: label(&text),
                icon_data: icon_data(icon),
                checked,
                enabled: false,
                ..Default::default()
            }
            .into(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_label_escapes_underscores() {
        assert_eq!(label("enp0s31f6_vlan"), "enp0s31f6__vlan");
    }

    #[test]
    fn test_menu_actions_become_tray_events() {
        assert_eq!(
            event_for(MenuAction::OpenDashboard),
            TrayEvent::OpenDashboard
        );
        assert_eq!(event_for(MenuAction::OpenSettings), TrayEvent::OpenSettings);
        assert_eq!(
            event_for(MenuAction::Command(Command::Disarm(60))),
            TrayEvent::Command(Command::Disarm(60))
        );
        assert_eq!(event_for(MenuAction::Quit), TrayEvent::Quit);
    }

    fn icon_keys(entries: &[Entry], out: &mut Vec<&'static str>) {
        for entry in entries {
            match entry {
                Entry::Header { icon, .. }
                | Entry::Action { icon, .. }
                | Entry::Radio { icon, .. }
                | Entry::Check { icon, .. } => out.push(icon),
                Entry::Submenu { icon, children, .. } => {
                    out.push(icon);
                    icon_keys(children, out);
                }
                Entry::Info(_) | Entry::Separator => {}
            }
        }
    }

    #[test]
    fn test_every_menu_icon_key_is_embedded() {
        let watching: Status = serde_json::from_value(serde_json::json!({
            "armed": true, "mode": "enforce", "usb_watching": true, "thunderbolt_watching": true,
            "sdcard_watching": true, "power_watching": true, "network_watching": true,
            "lid_watching": true, "pci_watching": true, "display_watching": true
        }))
        .unwrap();
        // Nothing watched as well, so the unwatched bus icons are covered.
        let idle: Status =
            serde_json::from_value(serde_json::json!({"armed": true, "mode": "learn"})).unwrap();
        let states = [
            TrayState::Down { stalled: false },
            TrayState::Disarmed { secs_left: 60 },
            TrayState::KillPending {
                bus: "power".into(),
                reason: "AC power removed".into(),
                secs_left: 5,
            },
            TrayState::DryRun,
            TrayState::Learning,
            TrayState::Armed,
        ];
        let mut keys = Vec::new();
        for state in &states {
            for status in [&watching, &idle] {
                icon_keys(&menu::build(state, Some(status), None), &mut keys);
            }
        }
        for key in &keys {
            assert!(!icon_data(key).is_empty(), "{key} has no embedded png");
        }
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), MENU_ICONS.len(), "unused icons: {keys:?}");
    }

    #[test]
    fn test_tray_starts_down_and_asks_for_attention() {
        let (tx, _rx) = async_channel::unbounded();
        let tray = PlugkillTray::new(String::new(), tx);
        assert_eq!(tray.state, TrayState::Down { stalled: false });
        assert!(matches!(
            ksni::Tray::status(&tray),
            ksni::Status::NeedsAttention
        ));
        assert_eq!(ksni::Tray::icon_name(&tray), "plugkill-down-symbolic");
    }
}
